/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCheckTag: typeof import('tdesign-mobile-vue')['CheckTag']
    TDrawer: typeof import('tdesign-mobile-vue')['Drawer']
    TFab: typeof import('tdesign-mobile-vue')['Fab']
    TGrid: typeof import('tdesign-mobile-vue')['Grid']
    TGridItem: typeof import('tdesign-mobile-vue')['GridItem']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TLink: typeof import('tdesign-mobile-vue')['Link']
    TList: typeof import('tdesign-mobile-vue')['List']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TSwitch: typeof import('tdesign-mobile-vue')['Switch']
    TTab: typeof import('tdesign-mobile-vue')['Tab']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
